import { Injector } from '@angular/core';
import { UntypedFormBuilder, UntypedFormGroup } from '@angular/forms';
import { Store } from '@ngrx/store';
import { AppState } from '../../../../../../../../../../thingsboard/ui-ngx/src/app/core/core.state';
import { BasicWidgetConfigComponent } from '../../../../../../../../../../thingsboard/ui-ngx/src/app/modules/home/components/widget/config/widget-config.component.models';
import { WidgetConfigComponentData } from '../../../../../../../../../../thingsboard/ui-ngx/src/app/modules/home/models/widget-component.models';
import { DataKey } from '../../../../../../../../../../thingsboard/ui-ngx/src/app/shared/models/widget.models';
import { WidgetConfigComponent } from '../../../../../../../../../../thingsboard/ui-ngx/src/app/modules/home/components/widget/widget-config.component';
import * as i0 from "@angular/core";
export declare class SignalStrengthBasicConfigComponent extends BasicWidgetConfigComponent {
    protected store: Store<AppState>;
    protected widgetConfigComponent: WidgetConfigComponent;
    private $injector;
    private fb;
    get displayTimewindowConfig(): boolean;
    onlyHistoryTimewindow(): boolean;
    signalStrengthLayouts: import("../../../../../../../../../../thingsboard/ui-ngx/src/app/modules/home/components/widget/lib/indicator/signal-strength-widget.models").SignalStrengthLayout[];
    signalStrengthLayoutTranslationMap: Map<import("../../../../../../../../../../thingsboard/ui-ngx/src/app/modules/home/components/widget/lib/indicator/signal-strength-widget.models").SignalStrengthLayout, string>;
    signalStrengthLayoutImageMap: Map<import("../../../../../../../../../../thingsboard/ui-ngx/src/app/modules/home/components/widget/lib/indicator/signal-strength-widget.models").SignalStrengthLayout, string>;
    signalStrengthWidgetConfigForm: UntypedFormGroup;
    datePreviewFn: any;
    tooltipValuePreviewFn: any;
    tooltipDatePreviewFn: any;
    constructor(store: Store<AppState>, widgetConfigComponent: WidgetConfigComponent, $injector: Injector, fb: UntypedFormBuilder);
    protected configForm(): UntypedFormGroup;
    protected defaultDataKeys(configData: WidgetConfigComponentData): DataKey[];
    protected onConfigSet(configData: WidgetConfigComponentData): void;
    protected prepareOutputConfig(config: any): WidgetConfigComponentData;
    protected validatorTriggers(): string[];
    protected updateValidators(emitEvent: boolean, trigger?: string): void;
    private getCardButtons;
    private setCardButtons;
    private _datePreviewFn;
    private _tooltipValuePreviewFn;
    private _tooltipDatePreviewFn;
    static ɵfac: i0.ɵɵFactoryDeclaration<SignalStrengthBasicConfigComponent, never>;
    static ɵcmp: i0.ɵɵComponentDeclaration<SignalStrengthBasicConfigComponent, "tb-signal-strength-basic-config", never, {}, {}, never, never, false, never>;
}
