import { ChangeDetectorRef, OnInit } from '@angular/core';
import { WidgetContext } from '../../../../../../../../../thingsboard/ui-ngx/src/app/modules/home/models/widget-component.models';
import { DatePipe } from '@angular/common';
import { ColorProcessor, ComponentStyle, DateFormatProcessor } from '../../../../../../../../../thingsboard/ui-ngx/src/app/modules/home/components/widget/config/widget-settings.models';
import { ValueCardLayout, ValueCardWidgetSettings } from './value-card-widget.models';
import { WidgetComponent } from '../../../../../../../../../thingsboard/ui-ngx/src/app/modules/home/components/widget/widget.component';
import * as i0 from "@angular/core";
export declare class ValueCardWidgetComponent implements OnInit {
    private date;
    private widgetComponent;
    private cd;
    settings: ValueCardWidgetSettings;
    valueCardLayout: typeof ValueCardLayout;
    ctx: WidgetContext;
    layout: ValueCardLayout;
    showIcon: boolean;
    icon: string;
    iconStyle: ComponentStyle;
    iconColor: ColorProcessor;
    showLabel: boolean;
    label: string;
    labelStyle: ComponentStyle;
    labelColor: ColorProcessor;
    valueText: string;
    valueStyle: ComponentStyle;
    valueColor: ColorProcessor;
    showDate: boolean;
    dateFormat: DateFormatProcessor;
    dateStyle: ComponentStyle;
    dateColor: ColorProcessor;
    backgroundStyle: ComponentStyle;
    overlayStyle: ComponentStyle;
    private horizontal;
    private decimals;
    private units;
    constructor(date: DatePipe, widgetComponent: WidgetComponent, cd: ChangeDetectorRef);
    ngOnInit(): void;
    onInit(): void;
    onDataUpdated(): void;
    static ɵfac: i0.ɵɵFactoryDeclaration<ValueCardWidgetComponent, never>;
    static ɵcmp: i0.ɵɵComponentDeclaration<ValueCardWidgetComponent, "tb-value-card-widget", never, { "ctx": "ctx"; }, {}, never, never, false, never>;
}
